apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx2-html
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Fecha y hora</title>
      <style>
        body {
          margin: 0;
          height: 100vh;
          display: flex;
          justify-content: center;
          align-items: center;
          background-color: blue;
          color: white;
          font-family: Arial, sans-serif;
        }
        #clock {
          font-size: 3rem;
          text-align: center;
        }
      </style>
    </head>
    <body>
      <div id="clock"></div>
      <script>
        function updateClock() {
          const now = new Date();
          document.getElementById("clock").innerHTML = now.toLocaleString();
        }
        setInterval(updateClock, 1000);
        updateClock();
      </script>
    </body>
    </html>